---

- name: download files
  hosts: bastion
  gather_facts: False
  vars_files:
    - group_vars/ocp
  
  tasks:
  - name: Create a directory if it does not exist
    file:
      path: "{{ download_loc }}"
      state: directory
      mode: '0777'

  - name: Download coreos raw
    get_url:
      url: "{{ rhcos.src }}"
      dest: "{{ download_loc }}/coreos.raw.gz"
      mode: '0755'
  
  - name: Download OCP installer
    get_url:
      url: "{{ }}"
      dest: "{{ download_loc }}/coreos.raw.gz"
      mode: '0755'