---
# Turn off openshift nodes
- name: Login
  hosts: localhost
  gather_facts: false
  # environment:
  #   KUBECONFIG: "/home/user1/.kube/config-kubeadmin"
  tasks:
    - name: Get and print nodes
      tags: check_nodes
      block:
        - name: login
          tags: check_nodes
          ansible.builtin.command: oc login https://api.ocp.edwin.home:6443 --insecure-skip-tls-verify=true -u  -p 

        - name: Get nodes status
          tags: check_nodes
          ansible.builtin.command: oc get nodes
          register: oc_get_nodes

        - name: Print nodes status
          tags: check_nodes
          ansible.builtin.debug:
            var: oc_get_nodes.stdout_lines