all:
  children:
    bastion:
      hosts:
        bastion.edwin.home:
          ansible_host: 192.168.31.10
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/ansible-key
    ocp:
      hosts:
        ocp.edwin.home:
          ansible_host: 192.168.31.20
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/ansible-key
    webserver:
      children:
        bastion:
    dnsserver:
      children:
        bastion:
    haproxy:
      children:
        bastion: