---
#Openshift oc login

- name: oc login
  command: oc login -u=${OCP_USER} -p=${OCP_PWD} --server={{ OCP_SERVER }} --insecure-skip-tls-verify

- name: oc login
  shell: oc -n openshift-kube-apiserver-operator get secret kube-apiserver-to-kubelet-signer -o jsonpath='{.metadata.annotations.auth\.openshift\.io/certificate-not-after}' | date -d -
  register: expdate
- debug:
    msg: "{{ expdate }}"
  failed_when: expdate < $(date -d "+7 days")