---

- name: Port checking - http
  wait_for:
    host: bastion
    port: 8080
    timeout: 5

- name: Port checking - https
  wait_for:
    host: bastion
    port: 443
    timeout: 5

- name: Port checking - http
  wait_for:
    host: bastion
    port: 80
    timeout: 5

- name: Port checking - master
  wait_for:
    host: bastion
    port: 6443
    timeout: 5

- name: Port checking - etcd
  wait_for:
    host: bastion
    port: 22623
    timeout: 5