---

- name: Verify DNS A records
  debug:
    msg: "{{lookup('dig', '{{ item.hostname }}.{{ cluster_name }}.{{ base_domain }}')}}"
  register: result
  failed_when: result.msg != item.ip
  with_items:
    - "{{ bootstrap_node }}"
    - "{{ master_nodes }}"
    - "{{ router_nodes }}"
    - "{{ infra_nodes }}"
    - "{{ etcd_nodes }}"
    - "{{ loadbalancer }}"
    
- name: Verify DNS PTR records
  debug:
    msg: "{{lookup('dig', '{{ item.ip }}/PTR')}}"
  register: result
  vars:
    fqdn: "{{item.hostname}}.{{ cluster_name }}.{{ base_domain }}."
  failed_when: result.msg != fqdn
  with_items:
    - "{{ bootstrap_node }}"
    - "{{ master_nodes }}"
    - "{{ router_nodes }}"
    - "{{ infra_nodes }}" 

# - name: Verify DNS etcd SRV records
#   debug:
#     msg: "{{ lookup('dig', '_etcd-server-ssl._tcp.{{ cluster_name }}.{{ base_domain }}/SRV', 'flat=0', wantlist=True) | map(attribute='target') | list | join(',') }}"
#   register: result
#   vars:
#     fqdn: "{{item.hostname}}.{{ cluster_name }}.{{ base_domain }}."
#   failed_when: fqdn not in result
#   with_items: "{{ etcd_nodes }}"


    # - name: Verify DNS etcd SRV records
    #   debug:
    #     msg: "{{ item.target }} <> {{ hostlist }}"
    #   vars:
    #     hostlist: "{{ etcd_nodes | map(attribute='hostname') | list | join(',') }}"
    #   failed_when: item.target not in hostlist
    #   with_items: "{{ lookup('dig', '_etcd-server-ssl._tcp.{{ cluster_name }}.{{ base_domain }}/SRV', 'flat=0', wantlist=True) }}"
    #   loop_control:
    #     index_var: idx